### ISSUE TITLE
接口不能用了

### ISSUE THREAD

**Issue by cnzx219** [kira1928/douyu-recorder#6]
http://capi.douyucdn.cn/api/v1/room/
返回
{"error":1002,"msg":"","data":[]}

**Comment by kira1928** [comment]
@cnzx219 

嗯，我这个项目停滞了很久，期间斗鱼可能已经改变了接口的用法。
直播录制这方面，这个项目今后会改成内部调用 you-get https://github.com/soimort/you-get ，以后更新下载方法这方面的事情就都推给you-get的人好了，哼哼。

说起来，you-get的稳定版本和develop branch最新状态都不能正常录制斗鱼了，需要merge https://github.com/soimort/you-get/pull/1734 ，外加解决一下这个issue https://github.com/soimort/you-get/issues/1657
这个issue目前似乎没有pull request， 不过只是在正则表达式里加个反斜杠，可以参考youtube-dl的相关pull request自己改一下 https://github.com/rg3/youtube-dl/pull/11931/files
我就是用develop branch修改这两处以后就可以录制了，可以试试看。

**Comment by kira1928** [comment]
youtube-dl和you-get似乎功能都差不多。看斗鱼这事的反应速度，我用youtube-dl也许会更靠谱一点= =
